apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: manga-cloudflare
spec:
  secretName: manga-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: manga.loeber.live
  dnsNames:
  - manga.loeber.live
