apiVersion: v1
kind: Service
metadata:
  name: linkedin-bridge
  labels:
    app: linkedin-bridge
spec:
  type: ClusterIP
  selector:
    app: linkedin-bridge
  ports:
    - name: bridge
      port: 80
      targetPort: 29319
      protocol: TCP
