apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wandb-launch-agent
  name: mlops
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "pods/log"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
