apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base
namespace: services
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: k3d-homelab-server-0
  target:
    kind: Deployment
    name: wallabag
images:
- name: wallabag/wallabag
  newTag: 2.5.4
commonAnnotations:
  reloader.stakater.com/auto: "true"
