apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
  annotations:
    tailscale.com/hostname: "torrent"
spec:
  selector:
    app: qbittorrent
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
  loadBalancerClass: tailscale
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-tcp
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: traffic
      port: 6881
      targetPort: 6881
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-udp
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: traffic-udp
      port: 6881
      targetPort: 6881
      protocol: UDP
