apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onchange
spec:
  secretName: onchange-tlse
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: onchange.loeber.live
  dnsNames:
  - onchange.loeber.live
