apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-bridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: instagram-bridge
  template:
    metadata:
      labels:
        app: instagram-bridge
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: load-config
          image: docker.io/grubertech/envsubst:v1.2.0
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            - -c
            - |
              envsubst -no-empty -i /template/config.yaml.tmpl -o /load/config.yaml \
              && cp -f /load/config.yaml /data/config.yaml
          env:
            - name: BRIDGE_DB_USERNAME
              valueFrom: { secretKeyRef: { name: matrix.db-bridges.credentials.postgresql.acid.zalan.do, key: username } }
            - name: BRIDGE_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: matrix.db-bridges.credentials.postgresql.acid.zalan.do, key: password } }
            - name: SHARED_SECRET
              valueFrom: { secretKeyRef: { name: synapse-shared, key: SHARED_SECRET } }
          volumeMounts:
            - name: config
              mountPath: /data
            - name: temp-dir
              mountPath: /load
            - name: template
              mountPath: /template
              readOnly: true
          resources:
            limits:
              cpu: 320m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
        - name: generate-config
          image: dock.mau.dev/mautrix/instagram:v0.2.2
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          env:
            - name: MAUTRIX_DIRECT_STARTUP
              value: "true"
          args:
            - -c
            - |
              python3 -m mautrix_instagram \
              -g -c "/data/config.yaml" \
              -r "/bridges/instagram.yaml"
          volumeMounts:
            - name: config
              mountPath: /data
            - name: bridges
              mountPath: /bridges
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      containers:
        - name: bridge
          image: dock.mau.dev/mautrix/instagram:v0.2.2
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          env:
            - name: MAUTRIX_DIRECT_STARTUP
              value: "true"
          args:
            - -c
            - |
              python3 -m mautrix_instagram \
              -n -c "/data/config.yaml"
          ports:
            - name: bridge
              containerPort: 29330
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 29330
            periodSeconds: 15
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 29330
            periodSeconds: 5
            initialDelaySeconds: 10
          startupProbe:
            tcpSocket:
              port: 29330
            periodSeconds: 30
            initialDelaySeconds: 120
          volumeMounts:
            - name: config
              mountPath: /data
          resources:
            limits:
              cpu: 320m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
      - name: template
        configMap:
          name: instagram-bridge-config
          items:
          - key: config.yaml.tmpl
            path: config.yaml.tmpl
      - name: temp-dir
        emptyDir: {}
      - name: config
        persistentVolumeClaim:
          claimName: instagram-bridge-data
      - name: bridges
        persistentVolumeClaim:
          claimName: bridge-config-storage
