apiVersion: v1
kind: Service
metadata:
  name: instagram-bridge
  labels:
    app: instagram-bridge
spec:
  type: ClusterIP
  selector:
    app: instagram-bridge
  ports:
    - name: bridge
      port: 80
      targetPort: 29330
      protocol: TCP
