apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-bridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: steam-bridge
  template:
    metadata:
      labels:
        app: steam-bridge
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: load-config
          image: docker.io/grubertech/envsubst:v1.2.0
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            - -c
            - |
              envsubst -no-empty -i /template/config.yaml.tmpl -o /load/config.yaml \
              && cp -f /load/config.yaml /data/config.yaml
          env:
            - name: SHARED_SECRET
              valueFrom: { secretKeyRef: { name: synapse-shared, key: SHARED_SECRET } }
          volumeMounts:
            - name: config
              mountPath: /data
            - name: temp-dir
              mountPath: /load
            - name: template
              mountPath: /template
              readOnly: true
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
        - name: generate-config
          image: grubertech/steam-bridge:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_PATH
              value: "/data/config.yaml"
            - name: REGISTRATION_PATH
              value: "/bridges/steam.yaml"
            - name: REG_GENERATE
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /data
            - name: bridges
              mountPath: /bridges
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      containers:
        - name: bridge
          image: grubertech/steam-bridge:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_PATH
              value: "/data/config.yaml"
            - name: REGISTRATION_PATH
              value: "/bridges/steam.yaml"
          ports:
            - name: bridge
              containerPort: 6000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6000
            periodSeconds: 15
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 6000
            periodSeconds: 5
            initialDelaySeconds: 10
          startupProbe:
            tcpSocket:
              port: 6000
            periodSeconds: 30
            initialDelaySeconds: 120
          volumeMounts:
            - name: config
              mountPath: /data
            - name: bridges
              mountPath: /bridges
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
      - name: template
        configMap:
          name: steam-bridge-config
          items:
          - key: config.yaml.tmpl
            path: config.yaml.tmpl
      - name: temp-dir
        emptyDir: {}
      - name: config
        persistentVolumeClaim:
          claimName: steam-bridge-data
      - name: bridges
        persistentVolumeClaim:
          claimName: bridge-config-storage
