apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-monitoring
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/zloeber/homelab.git'
    path: appset1/monitoring/longhorn
    targetRevision: main
  destination:
    namespace: longhorn-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - ApplyOutOfSyncOnly=true
    - Prune=false
    - Replace=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
