apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi
spec:
  secretName: unifi-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: unifi.loeber.live
  dnsNames:
    - unifi.loeber.live
