apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-cloudflare
spec:
  secretName: n8n-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: n8n.loeber.live
  dnsNames:
    - n8n.loeber.live
