apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wandb-cloudflare
spec:
  secretName: wandb-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ai.loeber.live
  dnsNames:
  - ai.loeber.live
