apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/zloeber/homelab/appset1/networking/tailscale/proxy
- https://github.com/zloeber/homelab/appset1/networking/tailscale
- https://github.com/zloeber/homelab/appset1/networking/cloudflared

patchesStrategicMerge:
- overlay/cloudflared-cm.yaml

namespace: matrix

patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/volumes/0/secret/secretName"
      value: "matrix-tunnel"
  target:
    kind: Deployment
    name: cloudflared
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: k3d-homelab-server-0
  target:
    kind: Deployment
    name: ts-proxy
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/2"
      value:
        name: TS_HOSTNAME
        value: "matrix"
    - op: replace
      path: "/spec/template/spec/containers/0/env/3"
      value:
        name: DEST_PORT
        value: "8008"
    - op: replace
      path: "/spec/template/spec/containers/0/env/4"
      value:
        name: TS_DEST_SVC
        value: "matrix-matrix-synapse.matrix.svc.cluster.local"
  target:
    kind: Deployment
    name: ts-proxy

commonAnnotations:
  reloader.stakater.com/auto: "true"
