apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wandb
spec:
  project: apps
  source:
    repoURL: 'https://github.com/zloeber/homelab.git'
    path: appset1/services/wandb
    targetRevision: main
  destination:
    namespace: mlops
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Replace=true
    - Prune=true
    retry:
      limit: 10
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 15m
