apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tanoshi-cloudflare
spec:
  secretName: tanoshi-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: read.loeber.live
  dnsNames:
  - read.loeber.live
