apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-sidecar
spec:
  template:
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:v1.34.1-2
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "tailscale logout; do sleep 1; done"]
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
            - name: TS_HOSTNAME
              value: "unifi"
            - name: DEST_PORT
              value: "8443"
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "150m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
