---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kured
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    resourceNames:
      - kured
    verbs:
      - update
