---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
spec:
  selector:
    matchLabels:
      name: kured
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kured
    spec:
      serviceAccountName: kured
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostPID: true
      restartPolicy: Always
      containers:
        - name: kured
          image: docker.io/weaveworks/kured:1.10.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /usr/bin/kured
            - '--ds-namespace=kube-system'
            - '--ds-name=kured'
            - '--time-zone=America/Sao_Paulo'
