apiVersion: v1
kind: Service
metadata:
  name: unifi-poller-svc
  labels:
    app: unifi-poller
spec:
  ports:
    - port: 9130
      targetPort: 9130
      protocol: TCP
      name: metrics
    - port: 9131
      targetPort: 37288
      protocol: TCP
      name: web
  selector:
    app: unifi-poller
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-poller-altsvc
spec:
  selector:
    app: unifi-poller
  type: NodePort
  ports:
    - port: 9130
      nodePort: 32767
      protocol: TCP
      name: metrics
