version: "3"
tasks:
  show:
    desc: "Show git variables"
    silent: true
    cmds:
      - |
        echo "AUTHOR_NAME: {{.AUTHOR_NAME}}"
        echo "AUTHOR_EMAIL: {{.AUTHOR_EMAIL}}"
        echo "ROOT_PATH: {{.ROOT_PATH}}"

  # init:submodule:
  #   desc: Iitialize all git submodules
  #   cmds:
  #     - |
  #       git submodule init
  #       git submodule update --recursive --init
  #       git submodule foreach 'git checkout master || git checkout main'  

  # init:
  #   desc: Initializes git with author information
  #   cmds:
  #     - |
  #       git config user.name "{{.AUTHOR_NAME}}"
  #       git config user.email "{{.AUTHOR_EMAIL}}"

  security:scan:
    desc: Perform security scan on local repo
    silent: true
    cmds:
    - |
      docker run --rm \
        -e "WORKSPACE=${PWD}" \
        -e ENABLE_OSS_RISK=true \
        -v $PWD:/app shiftleft/sast-scan scan \
        --src /app \
        --type credscan,nodejs,python,yaml,terraform,ansible,bash,dockerfile,bash,depscan \
        --out_dir /app/.local/reports
      echo "View results in ./.local/reports"

  gitleaks:
    desc: Perform gitleaks scan
    silent: true
    cmds:
    - |
      docker pull ghcr.io/zricethezav/gitleaks:latest
      docker run -v ${PWD}:/path zricethezav/gitleaks:latest \
        detect -r /path/.local/reports \
        --source="/path"
