---
version: '3'

tasks:
  html:
    deps:
      - :npm:install:typedoc
    desc: Generate TypeDoc HTML documentation
    cmds:
      - |
        ./scripts/log.sh info 'Generating documentation with TypeDoc'
        {{.NPX_HANDLE}}typedoc src/ --exclude "**/*.spec.ts" --out build/docs
        ./scripts/log.sh success 'Successfully generated technical documentation with TypeDoc'

  json:
    deps:
      - :npm:install:typedoc
    desc: Generate TypeDoc JSON documentation
    cmds:
      - |
        ./scripts/log.sh info 'Generating TypeDoc documentation in JSON format'
        {{.NPX_HANDLE}}typedoc src/ --exclude "**/*.spec.ts" --json build/docs/typedoc.json
        ./scripts/log.sh success 'Successfully generated JSON TypeDoc documentation'

  open:
    deps:
      - html
      - :npm:install:open-cli
    cmds:
      - |
        ./scripts/log.sh info 'Opening `build/docs/index.html` in the default browser'
        {{.NPX_HANDLE}}open-cli build/docs/index.html
