apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rpg.gruber@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector:
        dnsNames:
        - '*.loeber.live'
        - loeber.live
        - onchange.loeber.live
        - ai.loeber.live
        - home.loeber.live
        - monitoring.loeber.live
        - grafana.loeber.live
        - jupyter.loeber.live
        - ha.loeber.live
        - argo.loeber.live
        - chat.loeber.live
        - status.loeber.live
        - kuma.loeber.live
        - manga.loeber.live
        - books.loeber.live
        - finance.loeber.live
        - budget.loeber.live
        - n8n.loeber.live
        - unifi.loeber.live
        - lab.loeber.live
        - g.loeber.live
      dns01:
        cloudflare:
          email: rpg.gruber@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
