apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: operatorui=registry.opensource.zalan.do/acid/postgres-operator-ui
    argocd-image-updater.argoproj.io/operatorui.platforms: linux/amd64
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/zloeber/homelab.git'
    path: appset1/data/postgres/operator
    targetRevision: main
  destination:
    namespace: databases
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - ApplyOutOfSyncOnly=true
    - Prune=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
