apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: router
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/zloeber/homelab.git'
    path: apps/networking/tailscale/router
    targetRevision: main
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
