apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base

namespace: media

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: k3d-homelab-server-0
  target:
    kind: Deployment
    name: sonarr

commonAnnotations:
  reloader.stakater.com/auto: "true"
