apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkedin-bridge
spec:
  project: matrix
  source:
    repoURL: 'https://github.com/zloeber/homelab.git'
    path: apps/matrix/bridges/linkedin
    targetRevision: main
  destination:
    namespace: matrix
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
