apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: librex-cloudflare
spec:
  secretName: librex-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: g.loeber.live
  dnsNames:
  - g.loeber.live
